name: flutter_character_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  home_widget: ^0.9.0
  intl: ^0.19.0
  lottie: ^3.3.2
  mobx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
  fonts:
    - family: SulphurPoint
      fonts:
        - asset: assets/fonts/SulphurPoint-Regular.ttf
        - asset: assets/fonts/SulphurPoint-Light.ttf
        - asset: assets/fonts/SulphurPoint-Bold.ttf
